name: PlayingWithTime
main: io.github.mooeypoo.playingwithtime.PlayingWithTime
version: 1.0.3
description: Set permissions to your players based on time played in your server
author: mooeypoo
permissions:
   playingwithtime.ignore:
      description: Anyone with this permission will be ignored from the process of calculating time played on the server.
      default: op
   playingwithtime.cmd.process:
      description: This permission allows a user to run the "/playingwithtime process" command.
      default: op
   playingwithtime.cmd.reload:
      description: This permission allows a user to run the "/playingwithtime reload" command.
      default: op
commands:
   playingwithtime:
      description: Commands triggering actions in PlayingWithTime plugin.
      usage: Use `/playingwithtime help` to see the list of all available actions. 
